- hosts: master:worker
  tasks:
    - name: Copy spark dir
      synchronize:
        src: "{{ playbook_dir }}/"
        dest: spark/

- hosts: master
  tasks:
    - name: Add spark label for main node
      shell: 'docker node update --label-add spark.spark-data=true {{ main_node }}'

    - name: Deploy spark
      shell: 'docker stack deploy -c spark/docker-compose.yml spark'
      environment:
        - DOMAIN: '{{ spark_domain }}'
        - EXTERNAL_IP: '{{ spark_domain }}'
        - THRIFT_UI_DOMAIN: '{{ spark_thrift_ui_domain }}'
        - GARAGE_KEY_ID: '{{ garage_key_id | default("") }}'
        - GARAGE_SECRET_KEY: '{{ garage_secret_key | default("") }}'
      args:
        chdir: $HOME
