services:
  garage:
    image: dxflrs/garage:v1.0.1
    environment:
      - GARAGE_LOG_LEVEL=info
      - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET?Variable not set}
    volumes:
      - garage-data:/var/lib/garage/data
      - garage-meta:/var/lib/garage/meta
    configs:
      - source: garage-toml
        target: /etc/garage.toml
        mode: 0444
    networks:
      traefik-public:
        aliases:
          - garage
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.garage.garage-data == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.garage-s3-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.garage-s3-http.entrypoints=http
        - traefik.http.routers.garage-s3-http.middlewares=https-redirect
        - traefik.http.routers.garage-s3-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.garage-s3-https.entrypoints=https
        - traefik.http.routers.garage-s3-https.tls=true
        - traefik.http.routers.garage-s3-https.tls.certresolver=le
        - traefik.http.services.garage-s3.loadbalancer.server.port=3900

networks:
  traefik-public:
    external: true

volumes:
  garage-data:
  garage-meta:

configs:
  garage-toml:
    file: ./garage.toml
