
- hosts: master

  tasks:
    - name: Copy garage dir
      synchronize:
        src: "{{ playbook_dir }}/"
        dest: garage/

    - name: Add garage label for main node
      shell: 'docker node update --label-add garage.garage-data=true {{ main_node }}'

    - name: Deploy garage
      shell: 'docker stack deploy -c docker-compose.yml garage'
      environment:
        - DOMAIN: '{{ garage_domain }}'
        - GARAGE_RPC_SECRET: '{{ garage_rpc_secret }}'
      args:
        chdir: $HOME/garage
